const TabsData = [
  {
    title: "HTML",
    desc: "HTML stand for Hyper Text Markup Language,HTML is the standard language used to create and structure content on the web. It forms the backbone of web pages by organizing text, images, links, and other elements into a coherent document. HTML uses tags, which are special keywords enclosed in angle brackets (< >), to define the different elements of a page. Common tags include <p> for paragraphs, <h1> to <h6> for headings, and <a> for links. HTML is structured in a hierarchical format, with elements nested within one another to create the layout of a page.HTML alone doesn't define the appearance of the elements; it merely organizes them. The content of a webpage, like text and multimedia, is displayed according to the arrangement and hierarchy established by the HTML document. Attributes can be added to HTML tags to provide additional information about an element, such as href for links or src for images. Modern HTML5, the latest version of HTML, introduces several new features such as native audio and video embedding, semantic elements like <header> and <article>, and better support for web applications. HTML is the foundation of all websites, working together with CSS and JavaScript to create a full user experience.",
  },
  {
    title: "CSS",
    desc: "CSS (Cascading Style Sheets) is a stylesheet language used to control the appearance and layout of HTML elements on a web page. While HTML structures content, CSS handles its visual presentation, defining how elements like text, images, and divs are styled, including colors, fonts, margins, and spacing. The concept of 'cascading' in CSS allows styles to be applied from multiple sources, with priority rules determining which styles take effect when conflicts arise. This enables designers to create complex, responsive layouts that adapt to different screen sizes and devices.CSS uses selectors to target specific HTML elements or groups of elements. For example, a class selector (.classname) allows a developer to style all elements with a particular class, while an ID selector (#idname) targets a single unique element. CSS can be embedded directly in HTML, but it's more efficient to use external CSS files, which keep the style definitions separate from content structure, promoting better organization and maintainability.Modern CSS also includes powerful features like Flexbox and Grid for creating responsive layouts, as well as animations and transitions for dynamic effects. This makes CSS essential for creating visually appealing and interactive web pages without needing complex JavaScript.",
  },
  {
    title: "JavaScript",
    desc: "JavaScript is a programming language used to add interactivity and dynamic behavior to websites. avaScript (JS) is a versatile programming language primarily used to add dynamic functionality and interactivity to websites. It allows developers to create user-driven features like form validation, content updates, interactive maps, and animations that change in response to user actions. JavaScript is executed on the client side (within the browser), making it essential for building responsive, real-time experiences without needing to reload a web page. For example, a JavaScript function can validate a user's input in a form or display a pop-up message based on user behavior.JavaScript's power comes from its ability to manipulate the DOM (Document Object Model), which represents the structure of an HTML page. By using JavaScript, developers can dynamically alter the content, style, and structure of a webpage, such as hiding or showing elements, changing their style, or even completely reloading part of the page asynchronously (AJAX). JavaScript can be integrated directly into HTML files or linked as external files for better maintainability.",
  },
];
export default TabsData;
